name: ptablet
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter

  flex_color_scheme: ^7.1.2
  get: ^4.6.5
  google_fonts: ^6.2.1
  url_launcher: ^6.1.11
  network_to_file_image: ^6.0.1
  path_provider: ^2.0.15
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: true
  windows:
    generate: true

flutter:
  uses-material-design: true

assets:
  - images/icon/icon.png

